Repository paprika-spice/web-app, pull requests merged in 2018-02, with the labels that each got.

#24 Added basic headings
  index.html
Labels: content

#27 added Teri's heading
  index.html
Labels: content

#26 Fake learning branch simon
  index.html
Labels: content

#25 new heading added
  index.html
Labels: content

#37 Added type css content
  css/grid.css
  css/modules.css
  css/type.css
Labels: dev

#35 added css folder and modules.css
  css/modules.css
Labels: dev

#40 added initial css
  css/main.css
Labels: content, dev

#44 Jekyll-ifying
  _config.yml
  _layouts/default.html
  css/main.css
  images/ac-logo.svg
  images/icons.svg
  images/room-01.jpg
  images/room-02.jpg
  images/room-03.jpg
  images/room-04.jpg
  images/room-05.jpg
  images/room-06.jpg
  images/room-07.jpg
  images/workspace-logo-64.png
  index.html
Labels: content, dev
