Repository paprika-spice/web-app, pull requests merged in 2018-03, with the labels that each got.

#50 Book page
  book.html
  matches.html
Labels: dev

#51 Modified main.css, default jeykll layout, first booking page
  _layouts/default.html
  booking-step-1.html
  css/main.css
Labels: content, design, dev

#65 created second step
  booking-step-1.html
  booking-step-2.html
Labels: content, design, dev

#67 added favicon
  _layouts/default.html
  images/favicon.png
Labels: design, dev

#68 Export images for web
  images/room-01.jpg
  images/room-02.jpg
  images/room-03.jpg
  images/room-04.jpg
  images/room-05.jpg
  images/room-06.jpg
  images/room-07.jpg
Labels: design

#71 404 page
  404.html
  _layouts/default.html
  images/404.json
Labels: dev

#66 Login page
  login.html
Labels: dev

#72 Accessibility
  _layouts/default.html
  book-n206.html
  book-n210.html
  book-scworkpod.html
  book.html
  booking-completed.html
  booking-step-1.html
  booking-step-2.html
  edit-n206.html
  edit-roomcommons.html
  home.html
  login.html
  matches.html
Labels: dev

#73 The index needed to be the log in page
  index.html
  login.html
Labels: bug, content, dev

#75 removed home animation
  home.html
Labels: content, design

#83 changes
  index.html
Labels: bug

#84 / boi
  booking-step-1.html
Labels: bug

#85 fixed links
  booking-step-1.html
  booking-step-2.html
Labels: bug

#86 added tab-index labels to buttons and other major fields
  404.html
  book-n206.html
  book-n210.html
  book-scworkpod.html
  book.html
  booking-step-1.html
  booking-step-2.html
  edit-n206.html
  edit-roomcommons.html
  edit-scworkpod.html
  home-cancel.html
  home-success.html
  home.html
  index.html
  login.html
  matches.html
Labels: bug, dev

#88 white links
  _layouts/default-redirect.html
  _layouts/default.html
  css/main.css
Labels: design
